# Generated by Django 2.2.3 on 2019-07-19 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ericaconvin', '0002_auto_20190718_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='categorys',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ericaconvin.Category'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='locate',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='num',
            field=models.CharField(default='000-0000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
