# Generated by Django 2.2.3 on 2019-07-19 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ericaconvin', '0003_auto_20190719_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ericaconvin.Category'),
        ),
    ]
