# Generated by Django 2.1.8 on 2019-07-23 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ericaconvin', '0005_auto_20190719_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('num', models.CharField(default='000-0000-0000', max_length=15)),
                ('locate', models.CharField(default='', max_length=10)),
                ('cate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ericaconvin.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ericaconvin.Category'),
        ),
    ]
