# Generated by Django 2.1.8 on 2019-07-24 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ericaconvin', '0010_auto_20190724_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='img_address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ericaconvin.Category'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ericaconvin.Category'),
        ),
    ]
